import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  myaccountSidebar: [
    {
      type: "category",
      label: "Compute",
      link: {
        type: "doc",
        id: "myaccount/compute/index",
      },
      items: [
        {
          type: "category",
          label: "Nodes",
          className: "node",
          link: {
            type: "doc",
            id: "myaccount/nodes/README",
          },
          items: [
            {
              type: "category",
              label: "Overview",
              items: [
                "myaccount/nodes/concepts/what-is-the-node",
                {
                  type: "doc",
                  id: "myaccount/nodes/concepts/node-types-and-billing",
                  label: "Plans and Billing",
                },
                {
                  type: "doc",
                  id: "myaccount/nodes/concepts/networking-storage-and-security",
                  label: "Architecture",
                },
              ],
            },
            {
              type: "category",
              label: "Getting Started",
              items: [
                "myaccount/nodes/getting-started/overview",
                "myaccount/nodes/getting-started/prerequisites",
                "myaccount/nodes/getting-started/quickstart",
                {
                  type: "doc",
                  id: "myaccount/nodes/guides/create-your-first-node",
                  label: "Create a Node",
                },
              ],
            },
            {
              type: "category",
              label: "Workflows",
              items: [
                "myaccount/nodes/use-cases/launch-a-linux-app-server",
                "myaccount/nodes/use-cases/build-a-reusable-golden-image",
                "myaccount/nodes/use-cases/migrate-an-aws-image",
                "myaccount/nodes/use-cases/run-a-windows-domain-controller",
                "myaccount/nodes/use-cases/optimize-costs-with-e1-or-committed",
              ],
            },
            {
              type: "category",
              label: "Guides",
              items: [
                "myaccount/nodes/guides/marketplace-images",
                {
                  type: "doc",
                  id: "myaccount/nodes/guides/custom-images-and-migration",
                  label: "Custom Images",
                },
                "myaccount/nodes/guides/connect-to-your-node",
                {
                  type: "doc",
                  id: "myaccount/nodes/guides/windows-and-active-directory",
                  label: "Windows and AD",
                },
                "myaccount/nodes/guides/daily-operations",
                {
                  type: "doc",
                  id: "myaccount/nodes/guides/snapshots-images-and-backups",
                  label: "Snapshots and Backups",
                },
                "myaccount/nodes/guides/encryption",
                {
                  type: "doc",
                  id: "myaccount/nodes/guides/monitoring-and-alerts",
                  label: "Monitoring",
                },
                "myaccount/nodes/security",
              ],
            },
            {
              type: "category",
              label: "Troubleshooting",
              items: [
                {
                  type: "autogenerated",
                  dirName: "myaccount/nodes/troubleshooting",
                },
                "myaccount/nodes/faq",
              ],
            },
            {
              type: "category",
              label: "Reference",
              items: [
                {
                  type: "doc",
                  id: "myaccount/nodes/reference/configuration-reference",
                  label: "Configuration",
                },
                {
                  type: "doc",
                  id: "myaccount/nodes/reference/operations-reference",
                  label: "Operations",
                },
                {
                  type: "doc",
                  id: "myaccount/nodes/reference/support-matrix-and-limits",
                  label: "Limits",
                },
              ],
            },
          ],
        },
        {
          type: "doc",
          id: "myaccount/compute/gpu",
          label: "GPU (Internal)",
        },
        {
          type: "doc",
          id: "myaccount/compute/load-balancers",
          label: "Load Balancers",
        },
        {
          type: "doc",
          id: "myaccount/auto-scale/scaling",
          label: "Auto Scaling",
        },
        "myaccount/compute/kubernetes",
        "myaccount/compute/volumes",
        "myaccount/compute/images",
        "myaccount/compute/cdp-backups",
        {
          type: "doc",
          id: "myaccount/compute/eqs",
          label: "EQS (Internal)",
        },
        {
          type: "doc",
          id: "myaccount/compute/functions",
          label: "Functions (Internal)",
        },
      ],
    },
    {
      type: "category",
      label: "Storage",
      link: {
        type: "doc",
        id: "myaccount/storage/index",
      },
      items: [
        "myaccount/storage/scalable-file-system",
        "myaccount/storage/object-storage",
        "myaccount/storage/epfs",
      ],
    },
    {
      type: "category",
      label: "Database",
      link: {
        type: "doc",
        id: "myaccount/database/index",
      },
      items: ["myaccount/database/dbaas", "myaccount/database/parameter-group"],
    },
    {
      type: "category",
      label: "Network",
      link: {
        type: "doc",
        id: "myaccount/network/index",
      },
      items: [
        "myaccount/network/cdn",
        "myaccount/network/firewall",
        "myaccount/network/dns",
        "myaccount/network/reserve-ip",
        "myaccount/network/vpc",
        "myaccount/network/security-group",
        "myaccount/network/security-compliance",
      ],
    },
    {
      type: "category",
      label: "Disaster Recovery",
      link: {
        type: "doc",
        id: "myaccount/disaster-recovery/index",
      },
      items: [],
    },
    {
      type: "category",
      label: "Licenses",
      link: {
        type: "doc",
        id: "myaccount/licenses/index",
      },
      items: [
        "myaccount/licenses/license-management",
        "myaccount/licenses/ssl-certificates",
      ],
    },
    {
      type: "category",
      label: "Billing",
      link: {
        type: "doc",
        id: "myaccount/billing/index",
      },
      items: [
        "myaccount/billing/pay-now",
        "myaccount/billing/auto-pay",
        "myaccount/billing/account-statement",
        "myaccount/billing/manage-profile",
        "myaccount/billing/coupons",
        "myaccount/billing/tds",
      ],
    },
    {
      type: "category",
      label: "Settings",
      link: {
        type: "doc",
        id: "myaccount/settings/index",
      },
      items: [
        "myaccount/settings/audit-log",
        "myaccount/settings/security",
        "myaccount/settings/ssh-keys",
        "myaccount/settings/general-settings",
        "myaccount/settings/abuse-logs",
        "myaccount/settings/tags",
      ],
    },
    {
      type: "category",
      label: "Compliance",
      link: {
        type: "doc",
        id: "myaccount/compliances/index",
      },
      items: ["myaccount/compliances/compliance", "myaccount/compliances/eula"],
    },
    {
      type: "category",
      label: "Support",
      link: {
        type: "doc",
        id: "myaccount/support/index",
      },
      items: [
        "myaccount/support/abuse-support",
        "myaccount/support/soc-support",
        "myaccount/support/priority-platform",
        "myaccount/support/cloud-platform",
        "myaccount/support/sales-support",
      ],
    },
  ],
  tirSidebar: [
    {
      type: "category",
      label: "Overview",
      link: {
        type: "doc",
        id: "tir/index",
      },
      items: ["tir/getting-started/overview"],
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "doc",
          id: "tir/getting-started/quickstart",
          label: "Quickstart",
        },
      ],
    },
    {
      type: "category",
      label: "Workflows",
      items: [
        "tir/workflows/training",
        "tir/workflows/inference",
        "tir/workflows/research",
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: ["tir/guides/platform-paths", "tir/guides/billing-and-usage"],
    },
    {
      type: "category",
      label: "Troubleshooting",
      items: [
        {
          type: "doc",
          id: "tir/troubleshooting/support-and-release-notes",
          label: "Support and Updates",
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        {
          type: "doc",
          id: "tir/reference/platform-reference",
          label: "Platform Reference",
        },
      ],
    },
    {
      type: "link",
      label: "Extended TIR Docs",
      href: "https://docs.e2enetworks.com/docs/tir/",
    },
  ],
  helpSidebar: [
    {
      type: "doc",
      id: "help/index",
      label: "Overview",
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "help/godaddy/index",
        "help/godaddy/migrate",
        "help/godaddy/troubleshoot",
      ],
    },
  ],
};

export default sidebars;
